# Generated by Django 3.2.6 on 2021-08-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_rename_text_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='comment_created_date',
        ),
    ]
