# Generated by Django 3.2.6 on 2021-08-12 08:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_rename_created_date_comment_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comment.post'),
        ),
    ]
